---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - perl
      - python
      - java
      - bash
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "bin/*.pl"
  - "bin/*.py"
  - "bin/*.sh"
  - "bcgTreeGUI/src/**.java"
exclude_paths: []
